# Generated by Django 5.2.6 on 2025-09-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('idamonestacion', models.AutoField(db_column='idAmonestacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('fechaamonestacion', models.DateField(db_column='fechaAmonestacion')),
                ('motivo', models.CharField(max_length=150)),
                ('iddocumento', models.TextField(db_column='idDocumento')),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'amonestacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('idaspirante', models.AutoField(db_column='idAspirante', primary_key=True, serialize=False)),
                ('nombreaspirante', models.CharField(db_column='nombreAspirante', max_length=100)),
                ('apellidoaspirante', models.CharField(db_column='apellidoAspirante', max_length=100)),
                ('nit', models.CharField(max_length=9)),
                ('dpi', models.CharField(max_length=13)),
                ('genero', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'aspirante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('idausencia', models.AutoField(db_column='idAusencia', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('iddocumento', models.IntegerField(db_column='idDocumento')),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'ausencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('idcapacitacion', models.AutoField(db_column='idCapacitacion', primary_key=True, serialize=False)),
                ('nombreevento', models.CharField(db_column='nombreEvento', max_length=150)),
                ('lugar', models.CharField(max_length=150)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('institucionfacilitadora', models.CharField(db_column='institucionFacilitadora', max_length=150)),
                ('montoejecutado', models.DecimalField(db_column='montoEjecutado', decimal_places=2, max_digits=10)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(db_column='idContrato', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('tipocontrato', models.CharField(db_column='tipoContrato', max_length=50)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('idconvocatoria', models.AutoField(db_column='idConvocatoria', primary_key=True, serialize=False)),
                ('nombreconvocatoria', models.CharField(db_column='nombreConvocatoria', max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('estado', models.CharField(max_length=50)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'convocatoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterioevaluacion',
            fields=[
                ('idcriterioevaluacion', models.AutoField(db_column='idCriterioEvaluacion', primary_key=True, serialize=False)),
                ('nombrecriterio', models.CharField(db_column='nombreCriterio', max_length=100)),
                ('descripcioncriterio', models.CharField(db_column='descripcionCriterio', max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'criterioevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('iddocumento', models.AutoField(db_column='idDocumento', primary_key=True, serialize=False)),
                ('archivo', models.TextField()),
                ('nombrearchivo', models.CharField(db_column='nombreArchivo', max_length=150)),
                ('mimearchivo', models.CharField(db_column='mimeArchivo', max_length=10)),
                ('fechasubida', models.DateField(db_column='fechaSubida')),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('dpi', models.CharField(max_length=13)),
                ('nit', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('lugarnacimiento', models.CharField(db_column='lugarNacimiento', max_length=100)),
                ('fechanacimiento', models.DateField(db_column='fechaNacimiento')),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('estadocivil', models.CharField(db_column='estadoCivil', max_length=15)),
                ('numerohijos', models.IntegerField(db_column='numeroHijos')),
                ('numeroiggs', models.CharField(blank=True, db_column='numeroIggs', max_length=50, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleadocapacitacion',
            fields=[
                ('idempleadocapacitacion', models.AutoField(db_column='idEmpleadoCapacitacion', primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=150)),
                ('fechaenvio', models.DateField(db_column='fechaEnvio')),
                ('estado', models.CharField(max_length=50)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'empleadocapacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(db_column='idEquipo', primary_key=True, serialize=False)),
                ('idcoordinador', models.IntegerField(db_column='idCoordinador')),
                ('nombreequipo', models.CharField(db_column='nombreEquipo', max_length=100)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idevaluacion', models.AutoField(db_column='idEvaluacion', primary_key=True, serialize=False)),
                ('tipoevaluacion', models.CharField(db_column='tipoEvaluacion', max_length=100)),
                ('fechaevaluacion', models.DateTimeField(db_column='fechaEvaluacion')),
                ('puntajetotal', models.DecimalField(db_column='puntajeTotal', decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluacioncriterio',
            fields=[
                ('idevaluacioncriterio', models.AutoField(db_column='idEvaluacionCriterio', primary_key=True, serialize=False)),
                ('puntajecriterio', models.DecimalField(db_column='puntajeCriterio', decimal_places=2, max_digits=10)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'evaluacioncriterio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialpuesto',
            fields=[
                ('idhistorialpuesto', models.CharField(db_column='idHistorialPuesto', max_length=20, primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'historialpuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('ididioma', models.AutoField(db_column='idIdioma', primary_key=True, serialize=False)),
                ('nombreidioma', models.CharField(db_column='nombreIdioma', max_length=20)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Induccion',
            fields=[
                ('idinduccion', models.AutoField(db_column='idInduccion', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
                ('estado', models.CharField(max_length=20)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'induccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inducciondocumento',
            fields=[
                ('idinducciondocumento', models.AutoField(db_column='idInduccionDocumento', primary_key=True, serialize=False)),
                ('fechaasignado', models.DateField(db_column='fechaAsignado')),
                ('fechacompletado', models.DateField(blank=True, db_column='fechaCompletado', null=True)),
                ('idinforme', models.IntegerField(db_column='idInforme')),
                ('estado', models.CharField(max_length=20)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'inducciondocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('idpostulacion', models.AutoField(db_column='idPostulacion', primary_key=True, serialize=False)),
                ('fechapostulacion', models.DateField(db_column='fechaPostulacion')),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=150)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'postulacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pueblocultura',
            fields=[
                ('idpueblocultura', models.AutoField(db_column='idPuebloCultura', primary_key=True, serialize=False)),
                ('nombrepueblo', models.CharField(db_column='nombrePueblo', max_length=20)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'pueblocultura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('idpuesto', models.AutoField(db_column='idPuesto', primary_key=True, serialize=False)),
                ('nombrepuesto', models.CharField(db_column='nombrePuesto', max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('salariobase', models.DecimalField(db_column='salarioBase', decimal_places=2, max_digits=10)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'puesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='nombreRol', max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terminacionlaboral',
            fields=[
                ('idterminacionlaboral', models.AutoField(db_column='idTerminacionLaboral', primary_key=True, serialize=False)),
                ('tipoterminacion', models.CharField(db_column='tipoTerminacion', max_length=20)),
                ('fechaterminacion', models.DateField(db_column='fechaTerminacion')),
                ('observacion', models.CharField(max_length=150)),
                ('iddocumento', models.IntegerField(db_column='idDocumento')),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'terminacionlaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('idtipodocumento', models.AutoField(db_column='idTipoDocumento', primary_key=True, serialize=False)),
                ('nombretipo', models.CharField(db_column='nombreTipo', max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'tipodocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(db_column='nombreUsuario', max_length=100)),
                ('contrasena', models.CharField(max_length=150)),
                ('estado', models.TextField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
