# Generated by Django 5.2.6 on 2025-09-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('nombreestado', models.CharField(db_column='nombreEstado', max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.TextField()),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
    ]
